version: '2'
services:
  web:
    build: .
    image: culturagovbr/mapasculturais:1.0
    container_name: mapasculturais_web
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www
      # - ./app/:/var/www/mapasculturais
    links:
      - db:postgis
    environment:
      - PG_DB=mapasculturais
      - PG_PASS=mapasculturais
      - PG_USER=mapasculturais
      - PG_HOST=postgis
      - GIT_REPOSITORY=https://github.com/hacklabr/mapasculturais
  db:
    image: mdillon/postgis
    container_name: mapasculturais_database_postgres
    environment:
      - POSTGRES_DB=mapasculturais
      - POSTGRES_PASSWORD=mapasculturais
      - POSTGRES_USER=mapasculturais

  dependency_manager:
    image: composer:1.5.1
    restart: 'no'
    container_name: 'composer'
    command: install --prefer-dist
    volumes:
      - ./app/src/protected:/app
      # Share user and group
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

#

# version: '2'
# services:
#   web:
#     build: .
#     image: culturagovbr/salic-br:1.3
#     container_name: salic-br
#     ports:
#      - "80:80"
#      - "9000"
#     volumes:
#      - ./app:/var/www/salic-br
#      - ./log/apache2:/var/log/apache2
#      - ./app/public/txt:/var/www/salic-br/public/txt/
#      - ./app/public/plenaria:/var/www/salic-br/public/plenaria/
#     environment:
#      - APPLICATION_ENV=development
#      - XDEBUG_INSTALL="true"
#      - XDEBUG_REMOTE_ENABLE=on
#      - XDEBUG_REMOTE_AUTOSTART=on
#      - XDEBUG_REMOTE_HANDLER=dbgp
#      - XDEBUG_REMOTE_CONNECT_BACK=1
#      - XDEBUG_PROFILER_ENABLE=1
#      - XDEBUG_PROFILER_OUTPUT_DIR=/tmp/www/html
#      - XDEBUG_REMOTE_PORT=9000
#      - XDEBUGINI_PATH=/usr/local/etc/php/conf.d/xdebug.ini
#      - PHP_IDE_CONFIG="serverName=Test"
#      - XDEBUG_DEFAULT_ENABLE = 1
#      - XDEBUG_IDEKEY = "PHPSTORM"
# #    restart: always
#   dependency_manager:
#       image: composer:1.5.1
#       restart: 'no'
#       container_name: 'composer'
#       command: install
#       volumes:
#         - $PWD/app:/app
#         # Share user and group
#         - /etc/passwd:/etc/passwd:ro
#         - /etc/group:/etc/group:ro
